"""Qwen3-Embedding-0.6B query encoder for the v0+ compiler.

Implements the existing `EmbeddingClient` Protocol from `mcrs/embeddings/base.py`
so any consumer (compiler today, retrievers tomorrow) can swap encoders.

Mirrors the conventions used by `mcrs/retrieval_modules/bert.py` for the
8B sibling model:
- Model: `Qwen/Qwen3-Embedding-0.6B`
- Pooling: last_token (left-padded for batched inference)
- Normalization: L2

## Catalog encoding procedure — confirmed from source

The `metadata-qwen3_embedding_0.6b` column was generated by talkpl-ai with:

- **Document template** (from `talkenv/dataset/metadata.py::MetadataDataset.__getitem__`):
    ```
    music track, title:{track_name}, artist:{artist1, artist2, ...}, album:{album1, ...}
    ```
    The literal `"music track"` prefix is always present. Fields are conditional
    on non-empty value. `artist_name` and `album_name` are joined with `", "`;
    `track_name` is joined with `""` (no separator — that's what the code does).
    Use `TALKPLAY_METADATA_DOCUMENT_TEMPLATE` below to format a metadata dict
    the same way.
- **Tokenization**: raw text, no instruct prefix. `tokenizer(text, return_tensors="pt")`.
- **Pooling**: last-token with left-padding handling (standard Qwen3-Embedding).
- **Normalization**: NONE — saved as float32, un-normalized. If you want true
  cosine similarity, normalize BOTH sides at compare time.

Source: `talkpl-ai/talkplay-environment/talkenv/extractor/text/qwen3_embedding.py`
and `talkpl-ai/talkplay-environment/talkenv/dataset/metadata.py` on GitHub.

## Query encoding — what we do

For symmetric retrieval against this catalog, queries should also be raw text
with NO instruct prefix. That's the default. The opt-in `query_instruct`
parameter is kept for asymmetric-retrieval experiments — but the catalog was
NOT built that way, so default is empty.

See:
- HF model card: https://huggingface.co/Qwen/Qwen3-Embedding-0.6B
- Existing 8B-variant usage: `mcrs/retrieval_modules/bert.py`
- `mcrs/embeddings/base.py` for the Protocol
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


DEFAULT_MODEL = "Qwen/Qwen3-Embedding-0.6B"

# Empty by default — talkpl-ai's catalog was built without an instruct prefix,
# so queries should match.
DEFAULT_QUERY_INSTRUCT = ""

# Available for opt-in: kept around for asymmetric-retrieval experiments,
# but NOT what the catalog uses.
DEFAULT_QUERY_INSTRUCT_FOR_MUSIC_CRS = (
    "Instruct: Given a music recommendation conversation, retrieve relevant "
    "track metadata passages that match the listener request and prior music "
    "preferences.\nQuery: "
)


def talkplay_attributes_document_template(attributes: dict) -> str:
    """Format a track-attributes dict the same way talkpl-ai did when generating
    the `attributes-qwen3_embedding_0.6b` catalog column.

    Mirrors `talkpl-ai/talkplay-environment::talkenv/dataset/attributes.py`:

    ```
    music attributes, tags :{t1,t2,...}, tempo :{t1,t2,...}, key :{k1,k2,...}, chord :{c1,c2,...}
    ```

    Each clause appended only when the corresponding field is non-empty. The
    commented-out pseudo `caption` field is intentionally not included
    (matches upstream). Returns the empty string when all four fields are
    empty — upstream skips the embedding in that case.

    Note the space-before-colon convention (` :`) and the comma-only join
    inside each clause (no space after comma) — both are upstream quirks
    worth preserving for byte-identical reproduction.
    """
    parts: list[str] = []

    def _clause(field_value, label):
        if not field_value:
            return
        if isinstance(field_value, str):
            field_value = [field_value]
        joined = ",".join(str(v) for v in field_value)
        if joined:
            parts.append(f"{label} :{joined}")

    _clause(attributes.get("tags"), "tags")
    _clause(attributes.get("tempo"), "tempo")
    _clause(attributes.get("key"), "key")
    _clause(attributes.get("chord"), "chord")

    if not parts:
        return ""
    return "music attributes, " + ", ".join(parts)


def talkplay_lyrics_document_template(lyrics: str | None) -> str:
    """Format a lyrics blob the same way talkpl-ai did when generating the
    `lyrics-qwen3_embedding_0.6b` catalog column.

    Mirrors `talkpl-ai/talkplay-environment::talkenv/dataset/lyrics.py`:

    ```
    music lyrics :{lyrics}
    ```

    Returns the empty string when lyrics are empty / None — upstream skips
    the embedding in that case.
    """
    if not lyrics or not lyrics.strip():
        return ""
    return f"music lyrics :{lyrics}"


def talkplay_metadata_document_template(metadata: dict) -> str:
    """Format a track metadata dict the same way talkpl-ai did when generating
    the `metadata-qwen3_embedding_0.6b` catalog vectors.

    Mirrors `talkpl-ai/talkplay-environment::talkenv/dataset/metadata.py`
    exactly:

    ```
    music track, title:{track_name}, artist:{artist1, ...}, album:{album1, ...}
    ```

    - `"music track"` prefix is always present.
    - Each field is appended only if its value is non-empty.
    - `track_name` is joined with `""` (no separator); `artist_name` and
      `album_name` are joined with `", "`.

    Returns the empty string if all three fields are empty — matches the
    upstream behavior of skipping the embedding for such tracks.
    """
    text = "music track"
    has_any = False

    track_names = metadata.get("track_name") or []
    if isinstance(track_names, str):
        track_names = [track_names]
    if track_names:
        title = "".join(str(n) for n in track_names)
        text += f", title:{title}"
        has_any = True

    artist_names = metadata.get("artist_name") or []
    if isinstance(artist_names, str):
        artist_names = [artist_names]
    if artist_names:
        artist = ", ".join(str(n) for n in artist_names)
        text += f", artist:{artist}"
        has_any = True

    album_names = metadata.get("album_name") or []
    if isinstance(album_names, str):
        album_names = [album_names]
    if album_names:
        album = ", ".join(str(n) for n in album_names)
        text += f", album:{album}"
        has_any = True

    return text if has_any else ""


@dataclass
class Qwen3EmbeddingClient:
    """Local HF-backed query encoder. Implements `EmbeddingClient`."""

    model_name: str = DEFAULT_MODEL
    device: str = "cpu"
    torch_dtype_name: str = "float32"  # "float32" | "float16" | "bfloat16"
    max_length: int = 512
    batch_size: int = 8
    padding_side: str = "left"  # required for last_token pool on batches
    query_instruct: str = DEFAULT_QUERY_INSTRUCT

    # Internals (populated on first embed call)
    _model: Any = field(default=None, init=False, repr=False)
    _tokenizer: Any = field(default=None, init=False, repr=False)
    _torch: Any = field(default=None, init=False, repr=False)
    _F: Any = field(default=None, init=False, repr=False)

    # ------------------------------------------------------------------
    # Public surface
    # ------------------------------------------------------------------

    def embed_batch(self, texts: list[str]) -> list[list[float]]:
        if not texts:
            return []
        self._ensure_loaded()
        rendered = [self._render(t) for t in texts]
        out: list[list[float]] = []
        for start in range(0, len(rendered), self.batch_size):
            chunk = rendered[start : start + self.batch_size]
            tensor = self._encode_chunk(chunk)
            out.extend(tensor.detach().cpu().tolist())
        return out

    def embed_one(self, text: str) -> list[float]:
        return self.embed_batch([text])[0]

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _render(self, text: str) -> str:
        if self.query_instruct:
            return f"{self.query_instruct}{text}"
        return text

    def _ensure_loaded(self) -> None:
        if self._model is not None:
            return
        import torch
        import torch.nn.functional as F
        from transformers import AutoModel, AutoTokenizer

        self._torch = torch
        self._F = F
        dtype = _resolve_torch_dtype(self.torch_dtype_name)
        self._tokenizer = AutoTokenizer.from_pretrained(
            self.model_name, padding_side=self.padding_side
        )
        self._model = AutoModel.from_pretrained(
            self.model_name, torch_dtype=dtype
        ).to(self.device).eval()

    def _encode_chunk(self, texts: list[str]):
        torch = self._torch
        F = self._F
        with torch.inference_mode():
            batch = self._tokenizer(
                texts,
                padding=True,
                truncation=True,
                max_length=self.max_length,
                return_tensors="pt",
            )
            batch = {k: v.to(self.device) for k, v in batch.items()}
            outputs = self._model(**batch)
            pooled = _last_token_pool(
                outputs.last_hidden_state, batch["attention_mask"], torch=torch
            )
            return F.normalize(pooled, p=2, dim=1)


# ----------------------------------------------------------------------
# Pure helpers (testable without loading the model)
# ----------------------------------------------------------------------


def _last_token_pool(last_hidden_states, attention_mask, *, torch):
    """Last-token pooling for batched, possibly left-padded sequences.

    For left-padded batches (the Qwen3-Embedding convention) the last token
    of each sequence is at index -1 of the sequence axis. For right-padded
    batches we use the attention_mask to find each sequence's true last
    index.
    """
    left_padding = bool((attention_mask[:, -1].sum() == attention_mask.shape[0]).item())
    if left_padding:
        return last_hidden_states[:, -1]
    sequence_lengths = attention_mask.sum(dim=1) - 1
    batch_size = last_hidden_states.shape[0]
    return last_hidden_states[
        torch.arange(batch_size, device=last_hidden_states.device),
        sequence_lengths,
    ]


def _resolve_torch_dtype(name: str):
    import torch
    return {
        "float32": torch.float32,
        "fp32": torch.float32,
        "float16": torch.float16,
        "fp16": torch.float16,
        "bfloat16": torch.bfloat16,
        "bf16": torch.bfloat16,
    }.get(name.lower(), torch.float32)
